import { useContext, useEffect, useState } from "react";
import Navbar from "../components/navbar/Navbar";
import Sidebar from "../components/sidebar/Sidebar";
import { AuthProvider } from "../context/AuthContext";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Head from "next/head";

import "../styles/globals.css";
import UserRoute from "../context/routes/UserRoute";
import UserControl from "../context/routes/userControl";

function MyApp({ Component, pageProps }) {
  const [showChild, setShowChild] = useState(false);

  useEffect(() => {
    setShowChild(true);
  }, []);

  if (!showChild) {
    return null;
  }

  if (typeof window === "undefined") {
    return <></>;
  } else {
    return (
      <AuthProvider>
        <UserControl>
          <Head>
            <title>AdminPage</title>
            <meta name="description" content="Generated by create next app" />
          </Head>
          <div>
            <Navbar />
            <div className="appContainer">
              <UserRoute>
                <Sidebar />
              </UserRoute>
              <div className="appOthers">
                <ToastContainer position="top-center" />
                <Component {...pageProps} />
              </div>
            </div>
          </div>
        </UserControl>
      </AuthProvider>
    );
  }
}
export default MyApp;
